### PR TITLE
cli(upgrade): exit early if buildinfo matches

### LINKED ISSUE #1223: cli(upgrade): check controller version before running the upgrade
**Describe the bug**

Discovered while triaging #1217.

The `upgrade` command flow stops the opstrace controller (sets the number of replicas in the deployment to zero) and then proceeds to check the controller image tag version. If they don't match then the image tag version is updated and the deployment is restarted (sets the number of replicas back to one).

When the opstrace controller image tags match the number of replicas is never set back to one.

### PR DESCRIPTION
**Pull request by sreis**
Close #1223

Move the buildinfo version check to as early as possible and checks if the `cliMetadata.allCLIVersions` image tag of the Opstrace controller deployment matches the one defined in the CLI buildinfo. Older Opstrace versions will have an empty cliMetadata field, for these, check the Opstrace controller deployment image and check it matches buildinfo.

### CODE REVIEW

File: packages/upgrader/src/upgrade.ts [hunk 1]
```diff
@@ -43,31 +43,110 @@ import { waitForControllerDeployment } from "./readiness";
...
+    const idx = opstraceControllerConfig.cliMetadata.allCLIVersions.length - 1;
+    const lastCLIVersion =
+      opstraceControllerConfig.cliMetadata.allCLIVersions[idx].version;
+
+    const installedControllerImageTag = installedControllerVersion
+      ?.split(":")
+      .pop();
+    if (lastCLIVersion !== installedControllerImageTag) {
+      die(
+        `found Opstrace version mismatch, CLI version ${lastCLIVersion} does not match installed controller version ${installedControllerImageTag}`
```
Comment (jgehrcke) [inline packages/upgrader/src/upgrade.ts:78]: :+1: 

In this error message, "CLI version" sounds like "the version of the CLI that's currently being executed".

Maybe let's expose an implementation detail here and make sure the error message is "correct". This is like an `assert()` in code where we really think this invariant is never violated anyway. So when this blows up, the error message may be optimized for debuggability / ugly.

Let's maybe say "... lastCLIVersion in the controller config is ${lastCLIVersion}, and does not match ..."

**Comment by sreis** [comment]
Tests were stuck in the `cli-tests-with-cluster.sh` because of the DRY_RUN_UPGRADES test. I'll have a better look tomorrow but I'll probably remove that since we run the upgrade tests as part of the PRs.

**Comment by sreis** [comment]
AWS failed with instability #1059. Not related to the PR since the flake is related to Loki and the PR touches the upgrade command logic.
