### PR TITLE
chore: fix tsc compile error due to missing param

### LINKED ISSUE #1054: main branch broken: fails to compile: Argument of type 'true' is not assignable to parameter of type
**Describe the bug**

```
[2021-07-14T16:09:13Z] /build/packages/app/src/server/routes/api/cortex/cortexRuntimeConfig.ts
[2021-07-14T16:09:13Z] TypeScript error in /build/packages/app/src/server/routes/api/cortex/cortexRuntimeConfig.ts(133,51):
[2021-07-14T16:09:13Z] Argument of type 'true' is not assignable to parameter of type '{ forceUpdate?: boolean | undefined; forceCreate?: boolean | undefined; } | undefined'.  TS2345
[2021-07-14T16:09:13Z]
[2021-07-14T16:09:13Z]     131 |   const newcm = genCortexRuntimeConfigCM(KUBECONFIG, req.body);
[2021-07-14T16:09:13Z]     132 |   try {
[2021-07-14T16:09:13Z]   > 133 |     await createOrUpdateConfigMapWithRetry(newcm, true);
[2021-07-14T16:09:13Z]         |                                                   ^
[2021-07-14T16:09:13Z]     134 |   } catch (err) {
[2021-07-14T16:09:13Z]     135 |     // Expected error for invalid documents: response status
[2021-07-14T16:09:13Z]     136 |     // 422 Unprocessable Entity
[2021-07-14T16:09:13Z]
```

### PR DESCRIPTION
**Pull request by sreis**
Close #1054

### CODE REVIEW

**Comment by sreis** [comment]
AWS failed with know flake #920

File: packages/app/src/server/routes/api/cortex/cortexRuntimeConfig.ts [hunk 1]
```diff
@@ -130,7 +130,7 @@ export default async function setCortexRuntimeConfigHandler(
   // Assume that `req.body` is the new config map's payload content.
   const newcm = genCortexRuntimeConfigCM(KUBECONFIG, req.body);
   try {
-    await createOrUpdateConfigMapWithRetry(newcm, true);
+    await createOrUpdateConfigMapWithRetry(newcm, { forceUpdate: true });
```
Comment (jgehrcke) [inline packages/app/src/server/routes/api/cortex/cortexRuntimeConfig.ts:133]: Thank you!
