### PR TITLE
cli: dns service http client: work around err handling regression #1323 (includes: trigger-login-upon-401)

### LINKED ISSUE #1323: dns service client: 4xx errors may not be handled (all of them, always?) -- regression around `e instanceof got.RequestError`
https://buildkite.com/opstrace/upgrade-tests/builds/1259#de149bfb-607a-4fb0-80a7-77acdd3a7740/8243-9523

```
[2021-08-24T21:48:06Z] 2021-08-24T21:48:06.367Z [32minfo[39m: DNS service teardown: NS record query attempt 1: NS record set exists for upgrade-bk-1259-cb7-g.opstrace.io on the *.opstrace.io DNS zone.
[2021-08-24T21:48:06Z] 2021-08-24T21:48:06.367Z [34mdebug[39m: do DNS service client:DELETE
[2021-08-24T21:48:06Z] 2021-08-24T21:48:06.443Z [31merror[39m: error during cluster teardown (attempt 5):
[2021-08-24T21:48:06Z] HTTPError: Response code 404 (Not Found)
[2021-08-24T21:48:06Z]     at Request.<anonymous> (/snapshot/build/lib/utils/node_modules/got/dist/source/as-promise/index.js:117:42)
[2021-08-24T21:48:06Z]     at runMicrotasks (<anonymous>)
[2021-08-24T21:48:06Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[2021-08-24T21:48:06Z]   code: undefined,
[2021-08-24T21:48:06Z]   timings: [Object]
[2021-08-24T21:48:06Z] }
[2021-08-24T21:48:06Z] 2021-08-24T21:48:06.443Z [34mdebug[39m: `err?.stack`: HTTPError: Response code 404 (Not Found)
[2021-08-24T21:48:06Z]     at Request.<anonymous> (/snapshot/build/lib/utils/node_modules/got/dist/source/as-promise/index.js:117:42)
[2021-08-24T21:48:06Z]     at runMicrotasks (<anonymous>)
[2021-08-24T21:48:06Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2021-08-24T21:48:06Z] 2021-08-24T21:48:06.443Z [31merror[39m: JSON representation of err: {
[2021-08-24T21:48:06Z]   "name": "HTTPError",
[2021-08-24T21:48:06Z]   "timings": {
[2021-08-24T21:48:06Z]     "start": 1629841686368,
[2021-08-24T21:48:06Z]     "socket": 1629841686368,
[2021-08-24T21:48:06Z]     "lookup": 1629841686368,
[2021-08-24T21:48:06Z]     "connect": 1629841686376,
[2021-08-24T21:48:06Z]     "secureConnect": 1629841686389,
[2021-08-24T21:48:06Z]     "upload": 1629841686389,
[2021-08-24T21:48:06Z]     "response": 1629841686443,
[2021-08-24T21:48:06Z]     "end": 1629841686443,
[2021-08-24T21:48:06Z]     "phases": {
[2021-08-24T21:48:06Z]       "wait": 0,
[2021-08-24T21:48:06Z]       "dns": 0,
[2021-08-24T21:48:06Z]       "tcp": 8,
[2021-08-24T21:48:06Z]       "tls": 13,
[2021-08-24T21:48:06Z]       "request": 0,
[2021-08-24T21:48:06Z]       "firstByte": 54,
[2021-08-24T21:48:06Z]       "download": 0,
[2021-08-24T21:48:06Z]       "total": 75
[2021-08-24T21:48:06Z]     }
[2021-08-24T21:48:06Z]   }
[2021-08-24T21:48:06Z] }
[2021-08-24T21:48:06Z] 2021-08-24T21:48:06.444Z [31merror[39m: 5 attempt(s) failed. Stop retrying. Exit.
[2021-08-24T21:48:06Z] 2021-08-24T21:48:06.444Z [34mdebug[39m: shut down logger, then exit with code 1
[2021-08-24T21:48:06Z] make[1]: *** [Makefile:760: testupgrade-teardown] Error 1
[2021-08-24T21:48:06Z] make[1]: Leaving directory '/build'
```

### PR DESCRIPTION
**Pull request by jgehrcke**
Tested with mock service and in real world, trigger-login-upon-401 works again, tested during `opstrace create ...`:
```
2021-09-24T14:36:28.353Z info: setting up DNS
2021-09-24T14:36:29.258Z warning: DNS service client:GET failed: Response code 401 (Unauthorized)
2021-09-24T14:36:29.259Z info: perform another login to refresh authentication state
2021-09-24T14:36:29.259Z info: initiate device code login against https://opstrace-dev.us.auth0.com
```
This workaround should fix #1323. It is pretty sad that I do not understand the exact nature of this error handling problem.

It is unclear how the regression entered the system.

### CODE REVIEW

File: lib/dns/src/opstrace.ts [hunk 1]
```diff
@@ -385,9 +389,14 @@ export class DNSClient {
...
           // at this point, but maybe it does. Let's see, maybe it's better UX to
           // `die()`, here, too.
+          log.info(
+            "dns api: not an expected http error response, throw HighLevelRetry"
+          );
+
           throw new HighLevelRetry(`${action} failed`);
         }
 
+        log.info(`http err handler, throw: ${e.name} -- ${e.message}`);
```
Comment (jgehrcke) [inline lib/dns/src/opstrace.ts:399]: this log msg is bad -- will merge now anyway
