### PR TITLE
ci: fix controller image build

### LINKED ISSUE #247: controller not deploying correct app image
When we look at uishot-rootpage.png in the build artifacts then we see that the patch didn't take effect for the build. That's interesting.

The app image was rebuilt as part of the preamble, and this patch was generated:

```
[2021-01-06T16:55:56Z]    "prometheusOperator": "quay.io/prometheus-operator/prometheus-operator:v0.42.1",
[2021-01-06T16:55:56Z] -  "graphqlEngine": "opstrace/graphql:7232833b5b41ed1793caff32ca128926",
[2021-01-06T16:55:56Z] -  "app": "opstrace/app:7232833b5b41ed1793caff32ca128926",
[2021-01-06T16:55:56Z] +  "graphqlEngine": "opstrace/graphql:f79e575fd98938e009b5fc5f2f706b65",
[2021-01-06T16:55:56Z] +  "app": "opstrace/app:f79e575fd98938e009b5fc5f2f706b65",
[2021-01-06T16:55:56Z]    "redis": "bitnami/redis:6.0.9"
```

I haven't looked into this further from here.

CC @MatApple @sreis we need to watch out for this.

_Originally posted by @jgehrcke in https://github.com/opstrace/opstrace/issues/244#issuecomment-756087658_

### PR DESCRIPTION
**Pull request by sreis**
Fix #247 

Adds a test to check if the list of docker images in docker-images.json was deployed to the cluster.

### CODE REVIEW

**Comment by sreis** [comment]
GCP build failed with quota issues but the AWS build failed in the docker images check
 
```
> d run -ti opstrace/controller:5193a9d6-ci bash    
root@ffac623c1eae:/build/packages/controller# cd ..
root@ffac623c1eae:/build/packages# ls
config	controller  controller-config  tenants
root@ffac623c1eae:/build/packages# cat controller-config/
build/                package.json          src/                  tsconfig.json         tsconfig.tsbuildinfo  
root@ffac623c1eae:/build/packages# cat controller-config/src/
actions.ts          docker-images.json  docker-images.ts    errors.ts           index.ts            reducer/            tasks/              types.ts            utils.ts            
root@ffac623c1eae:/build/packages# cat controller-config/src/docker-images.json 
{
  "addonResizer": "k8s.gcr.io/addon-resizer:1.8.4",
  "certManagerCAInjector": "quay.io/jetstack/cert-manager-cainjector:v1.0.4",
  "certManagerController": "quay.io/jetstack/cert-manager-controller:v1.0.4",
  "cortex": "cortexproject/cortex:v1.6.0",
  "cortexApiProxy": "opstrace/cortex-api:7633d73fc9cf6af5d2caaa25d90fe242",
  "externalDNS": "k8s.gcr.io/external-dns/external-dns:v0.7.4",
  "systemlogFluentd": "opstrace/systemlog-fluentd:fe6d0d84-dev",
  "grafana": "grafana/grafana:7.3.4-ubuntu",
  "kubed": "appscode/kubed:v0.12.0",
  "kubeRBACProxy": "quay.io/coreos/kube-rbac-proxy:v0.4.1",
  "kubeStateMetrics": "quay.io/coreos/kube-state-metrics:v1.7.2",
  "localVolumeProvisioner": "quay.io/external_storage/local-volume-provisioner:v2.2.0",
  "loki": "grafana/loki:master-03aaa34",
  "lokiApiProxy": "opstrace/loki-api:7633d73fc9cf6af5d2caaa25d90fe242",
  "memcached": "memcached:1.6.6-alpine",
  "memcachedExporter": "prom/memcached-exporter:v0.6.0",
  "nginxController": "k8s.gcr.io/ingress-nginx/controller:v0.41.2",
  "nodeExporter": "quay.io/prometheus/node-exporter:v0.18.1",
  "prometheusAdapter": "quay.io/coreos/k8s-prometheus-adapter-amd64:v0.4.1",
  "prometheusOperator": "quay.io/prometheus-operator/prometheus-operator:v0.42.1",
  "graphqlEngine": "opstrace/graphql:f79e575fd98938e009b5fc5f2f706b65",
  "app": "opstrace/app:f79e575fd98938e009b5fc5f2f706b65",
  "redis": "bitnami/redis:6.0.9"
}
root@ffac623c1eae:/build/packages# 
```

Notice  `"app": "opstrace/app:f79e575fd98938e009b5fc5f2f706b65"` in the controller docker image  is the [expected image](https://buildkite.com/opstrace/prs/builds/3369#a582289f-784b-42ee-9c75-0e529e9ed980/1674-1766).

But the [check fails](https://buildkite.com/opstrace/prs/builds/3369#d5258c6b-a0e1-4390-8ac6-b57b64ef8652/4716-4769)  because the git repo was [reset before starting the aws/gcp tests](https://buildkite.com/opstrace/prs/builds/3369#d5258c6b-a0e1-4390-8ac6-b57b64ef8652/54-68).

File: ci/preamble.sh [hunk 1]
```diff
@@ -58,6 +52,12 @@ echo "--- Update docker-images.json"
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
 ${DIR}/build-docker-images-update-controller-config.sh
 
+# Do this early when the checkout is fresh (no non-repo files within /packages
+# or /lib as of previous tsc invocations -- these could erroenously invalidate
+# the controller image cache layers).
+echo "--- make build-and-push-controller-image"
+make build-and-push-controller-image
```
Comment (jgehrcke) [inline ci/preamble.sh:59]: Ha! Thank you @sreis for looking into this today!!!

**Comment by sreis** [comment]
GCP build failed with #62
