### PR TITLE
fix: no need to set/unset bash errexit

### LINKED ISSUE #115: CI build healthy but tests failed
**Describe the bug**

At least these two AWS CI runs were healthy but the tests failed.

https://buildkite.com/opstrace/scheduled-main-builds/builds/1307#94793a21-0bb4-4677-b286-68198da035b1/3094-5153
https://buildkite.com/opstrace/prs/builds/3165#6357df46-61ad-4aa0-bda7-881c7c8b0b14/2261-4062

**To Reproduce**

Not sure if it's AWS only.

**Expected behavior**

When tests fail the CI run must also fail.

### PR DESCRIPTION
**Pull request by sreis**
From https://linux.die.net/man/1/bash

"The shell does not exit if the command that fails is part of the command list immediately following a while or until keyword..."

Fix #115

### CODE REVIEW

**Comment by sreis** [comment]
PR does it's job since Loki tests failed and the AWS CI run is now unhealthy.

File: ci/deploy-testremote-teardown.sh [hunk 1]
```diff
@@ -218,7 +217,6 @@ do
         exit ${retcode}
     fi
 done
-set +e
```
Comment (jgehrcke) [inline ci/deploy-testremote-teardown.sh:221]: The meaning of the `+` and `-` is confusing, has often confused me. Was that the problem here that you wanted to temporarily _disable_ `errexit`, but accidentally disabled it for the rest of the program?

Comment (sreis) [reply ci/deploy-testremote-teardown.sh:221]: Exactly... n00b mistakes.

Comment (jgehrcke) [reply ci/deploy-testremote-teardown.sh:221]: `errexit`: sooo useful, soo powerful, soo dangerous :).
